# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asp_cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'asp_cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61sp_cluster.proto\x12\x0b\x61sp.cluster\"\x99\x01\n\x15PropagateBatchRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x30\n\x0einitial_states\x18\x02 \x03(\x0b\x32\x18.asp.cluster.StateVector\x12\x0f\n\x07t_final\x18\x03 \x01(\x01\x12\n\n\x02mu\x18\x04 \x01(\x01\x12\x0e\n\x06n_cheb\x18\x05 \x01(\x05\x12\x11\n\ttolerance\x18\x06 \x01(\x01\"!\n\x0bStateVector\x12\x12\n\ncomponents\x18\x01 \x03(\x01\"X\n\x16PropagateBatchResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12.\n\x07results\x18\x02 \x03(\x0b\x32\x1d.asp.cluster.TrajectoryResult\"|\n\x10TrajectoryResult\x12\x13\n\x0b\x66inal_state\x18\x01 \x03(\x01\x12\x14\n\x0cjacobi_error\x18\x02 \x01(\x01\x12\x10\n\x08nk_bound\x18\x03 \x01(\x01\x12\x14\n\x0cis_certified\x18\x04 \x01(\x08\x12\x15\n\rsegments_used\x18\x05 \x01(\x05\x32j\n\rOrbitDispatch\x12Y\n\x0ePropagateBatch\x12\".asp.cluster.PropagateBatchRequest\x1a#.asp.cluster.PropagateBatchResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asp_cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_PROPAGATEBATCHREQUEST']._serialized_start=35
  _globals['_PROPAGATEBATCHREQUEST']._serialized_end=188
  _globals['_STATEVECTOR']._serialized_start=190
  _globals['_STATEVECTOR']._serialized_end=223
  _globals['_PROPAGATEBATCHRESPONSE']._serialized_start=225
  _globals['_PROPAGATEBATCHRESPONSE']._serialized_end=313
  _globals['_TRAJECTORYRESULT']._serialized_start=315
  _globals['_TRAJECTORYRESULT']._serialized_end=439
  _globals['_ORBITDISPATCH']._serialized_start=441
  _globals['_ORBITDISPATCH']._serialized_end=547
# @@protoc_insertion_point(module_scope)
