# python/asp/_asp_core.pyi

import numpy as np
from typing import List, Tuple, Optional, Any

class PicardConfigPy:
    n_cheb: int
    tol: float
    max_iter: int
    ds_initial: float
    certify: bool
    max_segments: int
    def __init__(self) -> None: ...

class PicardSolverPy: ...

class PropagationResultPy:
    n_segments: int
    final_state: List[float]
    nk_bound_max: float
    jacobi_error: float
    last_seg_coeffs: List[float]
    coeff_rows: int
    coeff_cols: int

class LiftDiagnosisPy:
    bernstein_rho: float
    apply_fibration: bool
    suggested_ds: float

class KsCr3bpResultPy:
    n_segments: int
    jacobi_error: float
    final_cartesian: List[float]
    nk_bound_max: float
    bernstein_rho_mean: float

def chebyshev_fit(vals: np.ndarray) -> np.ndarray: ...
def chebyshev_integrate(c: np.ndarray, u_init: float, delta_s: float) -> np.ndarray: ...
def propagate_cr3bp_fast(x0: List[float], t_final: float, mu: float, n_cheb: Optional[int] = None, tol: Optional[float] = None) -> PropagationResultPy: ...
def cr3bp_jacobi(state: List[float], mu: float) -> float: ...
def estimate_s_from_t(t_final: float, x0: List[float], mu: float) -> float: ...
def propagate_ks_cr3bp(x0: List[float], s_final: float, mu: float, n_cheb: Optional[int] = None, tol: Optional[float] = None) -> KsCr3bpResultPy: ...
def diagnose_system(rhs: Any, x0: List[float], t0: float, dt_pilot: float, ndim: int) -> LiftDiagnosisPy: ...
def ks_map_py(u: List[float]) -> List[float]: ...
def ks_inverse_py(r: List[float]) -> List[float]: ...
def lc_map_py(u: List[float]) -> List[float]: ...
def lc_inverse_py(r: List[float]) -> List[float]: ...
def borel_pade_laplace_py(coeffs: List[float], z: float, n_gl: int) -> float: ...
def extract_singularities_py(coeffs: List[float]) -> List[float]: ...
def resurgent_pseudoinverse(a_func: Any, eps_min: float, eps_max: float, n_cheb: int) -> Tuple[np.ndarray, np.ndarray]: ...
def median_resummation_py(coeffs: List[float], z: float, epsilon: float, n_gl: int) -> float: ...
def auto_median_resummation_py(coeffs: List[float], z: float, n_gl: int) -> float: ...
def propagate_custom_c_abi(x0: List[float], t_final: float, rhs_ptr_val: int, jac_ptr_val: Optional[int] = None, uk_ptr_val: Optional[int] = None, n_cheb: Optional[int] = None, tol: Optional[float] = None, certify: Optional[bool] = None, propagate_stm: Optional[bool] = None) -> PropagationResultPy: ...
def compute_uk_force(m_arr: np.ndarray, a_arr: np.ndarray, b_arr: np.ndarray, q_arr: np.ndarray, tol: float) -> np.ndarray: ...
def compute_uk_force_identity(a_arr: np.ndarray, b_arr: np.ndarray, q_arr: np.ndarray, tol: float) -> np.ndarray: ...
def evaluate_clenshaw(coeffs: np.ndarray, tau: float) -> np.ndarray: ...
def compute_apc_collocation(moments: List[float], n_points: int) -> Tuple[List[float], List[float]]: ...