version: '3.8'
  
services:
  orbit_dispatch:
    build:
      context: .
      dockerfile: cmd/orbit_dispatch/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - asp_net
    environment:
      - RUST_WORKER_URL=rust_worker:50052
    depends_on:
      - rust_worker

  rust_worker:
    build:
      context: ../
      dockerfile: rust_worker.Dockerfile
    expose:
      - "50052"
    networks:
      - asp_net

networks:
  asp_net:
    driver: bridge